name: Build WPF App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.203' # hoặc version bạn đang dùng

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release

    - name: Publish WPF app
      shell: pwsh
      run: |
       dotnet publish WpfMvvmCustomerApp.csproj `
        --configuration Release `
        --output ./publish `
        -p:PublishSingleFile=true `
        -p:SelfContained=true `
        -p:RuntimeIdentifier=win-x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WPF-App
        path: ./publish

    - name: Bump version and create tag
      run: |
       git config user.name github-actions
       git config user.email github-actions@github.com
       git tag v1.0.${{ github.run_number }}
       git push origin v1.0.${{ github.run_number }}
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
       tag_name: v1.0.${{ github.run_number }}
       name: "Release v1.0.${{ github.run_number }}"
       body: "Auto-generated release"

